[tool.poetry]
name = "tetris"
version = "0.1.0"
description = ""
authors = ["Florian Bender <benderflorian70@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.0.0"
ansi = "^0.3.7"
keyboard = "^0.13.5"
scikit-image = "^0.24.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pre-commit = "^3.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = "py312"
src = ["src"]
lint.select = [
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "C4",  # flake8-comprehensions
    "I",   # isort
    "E",   # pycodestyle
]
lint.pydocstyle.convention = "google"
fix = true

[tool.mypy]
strict = true
warn_return_any = false
enable_incomplete_feature = "NewGenericSyntax"
