[tool.poetry]
name = "tetris"
version = "0.1.0"
description = ""
authors = ["Florian Bender <benderflorian70@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.0.0"
ansi = "^0.3.7"
keyboard = "^0.13.5"
scikit-image = "^0.24.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pre-commit = "^3.8.0"

[tool.poetry.scripts]
tetris = "tetris.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = "py312"
src = ["src"]
fix = true

[tool.ruff.lint]
pydocstyle.convention = "google"
select = ["ALL"]
ignore = [
    "D1",     # missing docstrings     (use own judgement)
    "COM812", # missing trailing comma (handled by formatter)
    "S101",   # assert used            (used only for things that should never fail and need no check in production)
]

[tool.ruff.lint.per-file-ignores]
"src/tetris/ui/cli/*" = ["T201"]                       # prints are allowed in CLI UI
"tests/*" = ["INP001"]                                 # we want no __init__.py files in tests
"tests/game_logic/test_action_counter.py" = ["FBT003"] # bool positional args

[tool.mypy]
strict = true
warn_return_any = false
enable_incomplete_feature = "NewGenericSyntax"
mypy_path = "src"
